# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'ObjcDemo' do
pod 'SDWebImage'

end


target 'SwiftDemo' do

pod 'SDWebImage'

end